Team6_pair2] Racing car step2 완료했습니다.
wwh-techcamp-2018/java-racingcar pull request #44
Opened 2018-07-03 08:08 UTC by chldbtjd2272

2018-07-03 08:48 UTC, javajigi requested changes
구현 잘 했네요. 피드백 남겼어요.

2018-07-03 08:48 UTC, javajigi commented on src/main/java/racing/game1/Car.java
> +        this.position = position;
set 메소드 대신 생성자를 사용해본다.

2018-07-03 08:48 UTC, javajigi commented on src/main/java/racing/game1/RacingGame.java
>  public class RacingGame {
RacingGame이 사용자에게 값을 입력받고, 결과를 출력하고, 로직을 구현하고..
너무 많은 일을 하고 있다. 객체가 한가지 역할만 가지도록 분리한다.
MVC 패턴 기반으로 구현하는 연습을 해본다.

2018-07-03 08:48 UTC, javajigi commented on src/main/java/racing/game1/RacingGame.java
> +        racingGame.total(time, (ArrayList) racingGame.cars);
casting을 사용하지 않는다.

2018-07-03 08:48 UTC, javajigi commented on src/main/java/racing/game1/Winner.java
> +        if (car.getPosition() > highScore) {
상태를 가지는 객체의 데이터를 꺼내려(get)하지 말고 객체에 메시지를 보내라는 원칙에 따라 구현한다.

2018-07-03 08:48 UTC, javajigi commented on src/main/java/racing/game1/Winner.java
> +        if (car.getPosition() == highScore) {
상태를 가지는 객체의 데이터를 꺼내려(get)하지 말고 객체에 메시지를 보내라는 원칙에 따라 구현한다.

2018-07-03 08:48 UTC, javajigi commented on src/main/java/racing/game1/Winner.java
> +            this.winners.append(car.getName());
메소드 이름과 하는 일이 다름.
메소드가 한 가지 일을 하는 것이 맞는가?

2018-07-03 09:30 UTC, chldbtjd2272 commented
[Team6_pair2] Racing car step2 완료했습니다.  피드백 내용 적용했습니다.

2018-07-04 09:46 UTC, javajigi approved these changes
계산기 구현 잘 했네요.

racingcar는 오전 피드백 잘 반영했네요. 💯 
몇 개 피드백 남겨 봤어요.

2018-07-04 09:46 UTC, javajigi commented on src/main/java/racing/game1/Car.java
> +    public void move() {
move() 메소드의 인자로 ValueGenerator가 전달되어 괜찮았을 것 같아요.
단, 피드백 반영해서 적용한 것은 👍

2018-07-04 09:46 UTC, javajigi commented on src/main/java/racing/game1/Car.java
> +        return false;
`return this.position == maxPosition`와 같이 한 라인으로 구현 가능.

2018-07-04 09:46 UTC, merged